config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#index'
  get '/emissions' => 'pages#emissions'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Business As Usual</title>
  <%= favicon_link_tag 'earth.ico' %>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

<%= yield %>

</body>
</html>

app/views/pages/emissions.html.erb
<%= link_to( image_tag('home.png', :class => 'icon'), root_path) %>
<button id="mapToggler" class="button">Which countries are most vulnerable?</button>

<div id="mapid">
</div>

<div id="search">
  <input type="text" class="search" placeholder="Australia">
  <a href="#" id="go" class="button">Search</a>
</div>



<%= image_tag('info.png', :class=> 'expandInfo') %>
<div class="moreInfo">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</div>

app/views/pages/index.html.erb
<p class="saganQuote">
  "There is perhaps no better demonstration of the folly of human conceits than this distant image of our tiny world. To me, it underscores our responsibility to deal more kindly with one another, and to preserve and cherish the pale blue dot, the only home we've ever known."<br><br>
  <span class="quoteName">Carl Sagan</span>
</p>

<span class="scrollToZoom">
  ^ Scroll to zoom ^
</span>

<div id="homeMenu">
  <p>
    Our pale blue dot is rapidly changing around us.
    Overuse of fossil fuels, land use, animal agriculture and deforestation have lead to an increase of temperatures and a degradation of oZone. As global temperatures rise, glaciers and arctic sea ice melt, sea levels rise, vegetation changes and economies suffer.<br><br>
    Some countries are bear greater responsibility for emitting more greenhouse gases, and some countries are more vulnerable to the effects of climate change.
  </p>
  <%= link_to 'see who\'s responsible  > ', emissions_path, :class => 'emissionsLink' %>

</div>